### ISSUE TITLE
Feature request: LED brightness

### ISSUE THREAD

**Issue by killerbees19** [jhubig/FritzBoxShell#23]
It's possible to set LED brightness (dimming) at some devices and/or with latest FRITZ!OS.

It would be nice if there's an action to adjust the brightness (1-3) of LEDs.

Currently I don't need this feature, therefore I'm only posting it as feature request without a PR.

(Reference: #22)

**Comment by jhubig** [comment]
Hello,

thanks for the request. I have added it for the moment (see https://github.com/jhubig/FritzBoxShell/commit/9890a59349dbbeeb915383fa6a9f51b1aa1067d6), but unfortunately I cannot test it because my model (FritzBox 7490). Would be happy to get some feedback from users having one of the units supporting it (current models which should have it):

- FritzBox 7590 AX
- FritzBox 7590
- FritzBox 6890 LTE

**Comment by jhubig** [comment]
WIth the help of @killerbees19 (thanks a lot 🥇 ) and his pull request https://github.com/jhubig/FritzBoxShell/pull/25, I would consider that issue to be solved.
